import { createRouter, createWebHistory } from 'vue-router'
import { routes } from './routes'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes,
})

// @vbr-insert-guards
// Auth guards (generated by vue-blocks-registry)
import { useAuthStore } from '@/modules/auth/store/useAuthStore'

router.beforeEach((to, _from, next) => {
  const requiresAuth = to.matched.some(r => r.meta?.requiresAuth)
  const requiresGuest = to.matched.some(r => r.meta?.requiresGuest)
  const auth = useAuthStore?.()
  const isAuthenticated = !!auth?.isAuthenticated
  if (requiresAuth && !isAuthenticated) return next({ name: 'login', query: { redirectTo: to.fullPath } })
  if (requiresGuest && isAuthenticated) return next({ name: 'dashboard' })
  next()
})

// Default guards placeholder. Configure auth store before enabling.
// See @registry/modules/auth for recommended integration.

// (Do not remove) – global guards can be injected here by CLI
// Example:
// router.beforeEach((to, _from, next) => {
//   const requiresAuth = to.matched.some(r => r.meta?.requiresAuth)
//   const requiresGuest = to.matched.some(r => r.meta?.requiresGuest)
//   const isAuthenticated = useAuthStore().isAuthenticated
//   if (requiresAuth && !isAuthenticated) return next({ name: 'login', query: { redirectTo: to.fullPath } })
//   if (requiresGuest && isAuthenticated) return next({ name: 'dashboard' })
//   next()
// })

export default router
