export const DEFAULT_MONITOR_BACKGROUND_REFETCH_INTERVAL_MS = 5 * 60 * 1000
export const DEFAULT_MONITOR_ACTIVE_REFETCH_INTERVAL_MS = 2 * 60 * 1000
export const DEFAULT_MONITOR_HEARTBEAT_INTERVAL_MS = 30 * 1000
