import type {
  TGearItemCategory,
  TGearItemPriority,
  TGearItemQuality,
  TGearItemStatus,
  TGearWeightUnit,
} from '../types/gear.types'
import type { TUUID } from '@/shared/types/base.type'

export interface IExampleSetItem {
  nameKey: string // Translation key for the item name
  catalogueItemId?: TUUID // Reference to global catalogue item (if item exists in catalogue)
  category: TGearItemCategory
  weight: number
  weightUnit: TGearWeightUnit
  quantity?: number
  priority?: TGearItemPriority
  status?: TGearItemStatus
  brand?: string
  notesKey?: string // Translation key for notes
  color?: string // Item color
  price?: number // Approximate price in USD
  currency?: string // Currency code (default: USD)
  url?: string // Product URL
  quality?: TGearItemQuality // Price tier / quality
  consumable?: boolean // Item is consumed/used up
}

// Fire Pouch items
export const firePouchItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.lightMyFireFiresteel',
    catalogueItemId: '01KBJXFP7WMDKNJ8HNMBW1CZZG', // Swedish FireSteel 2.0
    category: 'fire',
    weight: 28,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Light My Fire',
    notesKey: 'gear.sampleSet.items.lightMyFireFiresteel.notes',
    color: 'Orange',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.coghlansTinderQuik',
    category: 'fire',
    weight: 15,
    weightUnit: 'g',
    quantity: 3,
    priority: 'high',
    status: 'owned',
    brand: 'Coghlan\'s',
    notesKey: 'gear.sampleSet.items.coghlansTinderQuik.notes',
    color: 'Yellow',
    price: 5,
    currency: 'USD',
    quality: 'medium',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.bicLighter',
    catalogueItemId: '01KBJXGQ87FGHRFQTVMP3YFSNG', // BIC Classic Lighter
    category: 'fire',
    weight: 12,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'BIC',
    notesKey: 'gear.sampleSet.items.bicLighter.notes',
    color: 'Red',
    price: 2,
    currency: 'USD',
    quality: 'low',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.ucoStormproofMatches',
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ0', // UCO Stormproof Matches
    category: 'fire',
    weight: 25,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'UCO',
    notesKey: 'gear.sampleSet.items.ucoStormproofMatches.notes',
    color: 'Orange',
    price: 8,
    currency: 'USD',
    quality: 'high',
    consumable: true,
  },
]

// Bug Out Bag items
export const bugOutBagItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.moraknivCompanion',
    category: 'blades',
    weight: 120,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Morakniv',
    notesKey: 'gear.sampleSet.items.moraknivCompanion.notes',
    color: 'Orange',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.leathermanWave',
    catalogueItemId: '01KBJXH4VP0T1SAZADHD3KY0RY', // Leatherman Wave+
    category: 'tools',
    weight: 241,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'Leatherman',
    notesKey: 'gear.sampleSet.items.leathermanWave.notes',
    color: 'Silver',
    price: 120,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.fenixPD36R',
    category: 'light',
    weight: 145,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Fenix',
    notesKey: 'gear.sampleSet.items.fenixPD36R.notes',
    color: 'Black',
    price: 90,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.adventureMedicalKitsUltralight',
    category: 'firstAid',
    weight: 340,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Adventure Medical Kits',
    notesKey: 'gear.sampleSet.items.adventureMedicalKitsUltralight.notes',
    color: 'Red',
    price: 25,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.paracord550',
    category: 'tools',
    weight: 50,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'Generic',
    notesKey: 'gear.sampleSet.items.paracord550.notes',
    color: 'Black',
    price: 8,
    currency: 'USD',
    quality: 'medium',
  },
  {
    nameKey: 'gear.sampleSet.items.lifestrawPersonal',
    catalogueItemId: '01KBJXJ3P532DYZMJ0DK2K6MW1', // LifeStraw Personal Water Filter
    category: 'water',
    weight: 46,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'LifeStraw',
    notesKey: 'gear.sampleSet.items.lifestrawPersonal.notes',
    color: 'Blue',
    price: 20,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.solEmergencyBivvy',
    category: 'shelter',
    weight: 85,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'SOL (Survive Outdoors Longer)',
    notesKey: 'gear.sampleSet.items.solEmergencyBivvy.notes',
    color: 'Orange',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
]

// Bug Out Bag fire pouch items (nested container)
export const bugOutBagFirePouchItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.lightMyFireFiresteel',
    catalogueItemId: '01KBJXFP7WMDKNJ8HNMBW1CZZG', // Swedish FireSteel 2.0
    category: 'fire',
    weight: 28,
    weightUnit: 'g',
    priority: 'critical',
    status: 'owned',
    brand: 'Light My Fire',
    color: 'Orange',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.bicLighter',
    catalogueItemId: '01KBJXGQ87FGHRFQTVMP3YFSNG', // BIC Classic Lighter
    category: 'fire',
    weight: 12,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'BIC',
    color: 'Red',
    price: 2,
    currency: 'USD',
    quality: 'low',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.coghlansTinderQuik',
    category: 'fire',
    weight: 15,
    weightUnit: 'g',
    quantity: 2,
    priority: 'high',
    status: 'owned',
    brand: 'Coghlan\'s',
    color: 'Yellow',
    price: 5,
    currency: 'USD',
    quality: 'medium',
    consumable: true,
  },
]

// EDC items
export const edcItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.victorinoxClassicSD',
    category: 'blades',
    weight: 21,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'Victorinox',
    notesKey: 'gear.sampleSet.items.victorinoxClassicSD.notes',
    color: 'Red',
    price: 20,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.olightI3TEOS',
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ4', // Olight i3T EOS 2
    category: 'light',
    weight: 12,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'Olight',
    notesKey: 'gear.sampleSet.items.olightI3TEOS.notes',
    color: 'Black',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.zippoLighter',
    category: 'fire',
    weight: 55,
    weightUnit: 'g',
    priority: 'medium',
    status: 'owned',
    brand: 'Zippo',
    notesKey: 'gear.sampleSet.items.zippoLighter.notes',
    color: 'Chrome',
    price: 20,
    currency: 'USD',
    quality: 'high',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.fieldNotesNotebook',
    category: 'tools',
    weight: 80,
    weightUnit: 'g',
    priority: 'low',
    status: 'owned',
    brand: 'Field Notes',
    notesKey: 'gear.sampleSet.items.fieldNotesNotebook.notes',
    color: 'Tan',
    price: 10,
    currency: 'USD',
    quality: 'medium',
    consumable: true,
  },
  {
    nameKey: 'gear.sampleSet.items.fisherSpacePen',
    category: 'tools',
    weight: 8,
    weightUnit: 'g',
    priority: 'medium',
    status: 'owned',
    brand: 'Fisher',
    notesKey: 'gear.sampleSet.items.fisherSpacePen.notes',
    color: 'Black',
    price: 25,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.ankerPowerCore10000',
    catalogueItemId: '01KBJXKPDHSV3W2NNP222TVPZZ', // Anker PowerCore 20100 (closest match)
    category: 'communication',
    weight: 180,
    weightUnit: 'g',
    priority: 'high',
    status: 'owned',
    brand: 'Anker',
    notesKey: 'gear.sampleSet.items.ankerPowerCore10000.notes',
    color: 'Black',
    price: 30,
    currency: 'USD',
    quality: 'high',
  },
]

// Budget EDC Survival Kit
export const budgetEdcSurvivalKitItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.olightI3TEOS',
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ4', // Olight i3T EOS 2
    category: 'light',
    weight: 40,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'Olight',
    color: 'Black',
    price: 25,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.lightMyFireFiresteel',
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ5', // Light My Fire Swedish FireSteel 2.0
    category: 'fire',
    weight: 50,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'Light My Fire',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    catalogueItemId: '01KBQ9MKG60801WW461XE4JJA6', // Rite in the Rain All-Weather Notepad 3x5
    nameKey: 'gear.sampleSet.items.riteInTheRainNotepad',
    category: 'other',
    weight: 70,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'Rite in the Rain',
    color: 'Yellow',
    price: 6,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG60801WW461XE4JJA7', // Sharpie Permanent Marker
    nameKey: 'gear.sampleSet.items.sharpieMarker',
    category: 'other',
    weight: 9,
    weightUnit: 'g',
    quantity: 1,
    priority: 'low',
    status: 'owned',
    brand: 'Sharpie',
    color: 'Black',
    price: 2,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ1', // Compact Duct Tape
    nameKey: 'gear.sampleSet.items.ductTape',
    category: 'tools',
    weight: 100,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'Generic',
    price: 5,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ2', // Metal Spork
    nameKey: 'gear.sampleSet.items.metalSpork',
    category: 'tools',
    weight: 25,
    weightUnit: 'g',
    quantity: 1,
    priority: 'low',
    status: 'owned',
    brand: 'Generic',
    price: 8,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AYX', // CNOC Vecto Collapsible Water Bottle 1L
    nameKey: 'gear.sampleSet.items.cnocVectoBottle',
    category: 'water',
    weight: 40,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'CNOC',
    price: 12,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ0', // UCO Stormproof Matches
    nameKey: 'gear.sampleSet.items.ucoStormproofMatches',
    category: 'fire',
    weight: 25,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'UCO',
    price: 8,
    currency: 'USD',
    quality: 'high',
    consumable: true,
  },
  {
    catalogueItemId: '01KBQ9MKG60801WW461XE4JJA8', // Fenix E01 V2.0
    nameKey: 'gear.sampleSet.items.fenixE01',
    category: 'light',
    weight: 13,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'Fenix',
    color: 'Black',
    price: 20,
    currency: 'USD',
    quality: 'high',
  },
]

// Medium EDC / Urban Survival Kit
export const mediumEdcSurvivalKitItems: IExampleSetItem[] = [
  {
    nameKey: 'gear.sampleSet.items.olightI3TEOS',
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ4', // Olight i3T EOS 2
    category: 'light',
    weight: 40,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'Olight',
    color: 'Black',
    price: 25,
    currency: 'USD',
    quality: 'high',
  },
  {
    catalogueItemId: '01KBQ9MKG50801WW461XE4JJA4', // Victorinox Huntsman
    nameKey: 'gear.sampleSet.items.victorinoxHuntsman',
    category: 'tools',
    weight: 97,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'Victorinox',
    color: 'Red',
    price: 45,
    currency: 'USD',
    quality: 'high',
  },
  {
    nameKey: 'gear.sampleSet.items.lightMyFireFiresteel',
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ5', // Light My Fire Swedish FireSteel 2.0
    category: 'fire',
    weight: 50,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'Light My Fire',
    price: 15,
    currency: 'USD',
    quality: 'high',
  },
  {
    catalogueItemId: '01KBQ9MKG60801WW461XE4JJA6', // Rite in the Rain All-Weather Notepad 3x5
    nameKey: 'gear.sampleSet.items.riteInTheRainNotepad',
    category: 'other',
    weight: 70,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'Rite in the Rain',
    color: 'Yellow',
    price: 6,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG60801WW461XE4JJA7', // Sharpie Permanent Marker
    nameKey: 'gear.sampleSet.items.sharpieMarker',
    category: 'other',
    weight: 9,
    weightUnit: 'g',
    quantity: 1,
    priority: 'low',
    status: 'owned',
    brand: 'Sharpie',
    color: 'Black',
    price: 2,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AZ1', // Compact Duct Tape
    nameKey: 'gear.sampleSet.items.ductTape',
    category: 'tools',
    weight: 100,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'Generic',
    price: 5,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AYX', // CNOC Vecto Collapsible Water Bottle 1L
    nameKey: 'gear.sampleSet.items.cnocVectoBottle',
    category: 'water',
    weight: 40,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'CNOC',
    price: 12,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AYW', // Mil-Tec Emergency Thermal Blanket
    nameKey: 'gear.sampleSet.items.milTecEmergencyBlanket',
    category: 'shelter',
    weight: 50,
    weightUnit: 'g',
    quantity: 1,
    priority: 'high',
    status: 'owned',
    brand: 'Mil-Tec',
    price: 8,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG60801WW461XE4JJA5', // Ferrocerium Rod 8 mm
    nameKey: 'gear.sampleSet.items.ferroRod8mm',
    category: 'fire',
    weight: 35,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'Generic',
    price: 8,
    currency: 'USD',
    quality: 'medium',
  },
  {
    catalogueItemId: '01KBQ9MKG500FXNVND2X3J4AYZ', // GSI Outdoors Stainless Steel Cup 700 ml
    nameKey: 'gear.sampleSet.items.gsiStainlessCup',
    category: 'other',
    weight: 150,
    weightUnit: 'g',
    quantity: 1,
    priority: 'medium',
    status: 'owned',
    brand: 'GSI Outdoors',
    price: 15,
    currency: 'USD',
    quality: 'medium',
  },
  {
    // Note: FA001 (Basic Mini First Aid Kit) - assuming this exists in catalogue or will be added
    nameKey: 'gear.sampleSet.items.basicMiniFirstAidKit',
    category: 'firstAid',
    weight: 100,
    weightUnit: 'g',
    quantity: 1,
    priority: 'critical',
    status: 'owned',
    brand: 'Generic',
    price: 15,
    currency: 'USD',
    quality: 'medium',
  },
]

